development:
  adapter: postgresql
  database: accomplist_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: accomplist_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: accomplist_production
  pool: 5
  timeout: 500
